# Generated by Django 4.2.3 on 2023-07-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=10)),
                ('esalary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ejoiningdate', models.DateField()),
                ('eclosingdate', models.DateField()),
            ],
        ),
    ]
